### ISSUE TITLE
Higher Resolution Images?

### ISSUE THREAD

**Issue by aashishrai3799** [kaist-ami/Sound2Scene#1]
Hi, thanks for the amazing work! Could you please guide me on generating higher resolution images from the model?

Thanks!!

**Comment by sbkim052** [comment]
Hi, thanks for the interest. 
You need to train the Sound2Scene model with another version of the image decoder.
Instead of BigGAN (128x128), which we used for the image decoder, you download another version of BigGAN which generates 256x256 images, from the link below.

Please refer to the link below.
https://github.com/facebookresearch/ic_gan#python-script-generate-images-with-ic-gan
